"""Corpus fitted into the pipeline: well-known programming/CS quotes.

Only used at build time (build_pipeline.py). Not shipped to Modal — its
content lives baked into pipeline.joblib as the fitted document matrix.
"""

QUOTES = [
    {"text": "Any fool can write code that a computer can understand. Good programmers write code that humans can understand.", "author": "Martin Fowler"},
    {"text": "Premature optimization is the root of all evil.", "author": "Donald Knuth"},
    {"text": "There are only two hard things in Computer Science: cache invalidation and naming things.", "author": "Phil Karlton"},
    {"text": "Talk is cheap. Show me the code.", "author": "Linus Torvalds"},
    {"text": "The best way to predict the future is to invent it.", "author": "Alan Kay"},
    {"text": "Simplicity is the soul of efficiency.", "author": "Austin Freeman"},
    {"text": "Make it work, make it right, make it fast.", "author": "Kent Beck"},
    {"text": "First, solve the problem. Then, write the code.", "author": "John Johnson"},
    {"text": "Programs must be written for people to read, and only incidentally for machines to execute.", "author": "Harold Abelson"},
    {"text": "The most disastrous thing that you can ever learn is your first programming language.", "author": "Alan Kay"},
    {"text": "Software and cathedrals are much the same. First we build them, then we pray.", "author": "Unknown"},
    {"text": "Deleted code is debugged code.", "author": "Jeff Sickel"},
    {"text": "It's not a bug, it's an undocumented feature.", "author": "Unknown"},
    {"text": "Walking on water and developing software from a specification are easy if both are frozen.", "author": "Edward Berard"},
    {"text": "The computer was born to solve problems that did not exist before.", "author": "Bill Gates"},
    {"text": "A good programmer is someone who always looks both ways before crossing a one-way street.", "author": "Doug Linder"},
    {"text": "Java is to JavaScript what car is to Carpet.", "author": "Chris Heilmann"},
    {"text": "Debugging is twice as hard as writing the code in the first place.", "author": "Brian Kernighan"},
    {"text": "The only way to learn a new programming language is by writing programs in it.", "author": "Dennis Ritchie"},
    {"text": "Controlling complexity is the essence of computer programming.", "author": "Brian Kernighan"},
    {"text": "Testing shows the presence, not the absence of bugs.", "author": "Edsger Dijkstra"},
    {"text": "Simplicity is prerequisite for reliability.", "author": "Edsger Dijkstra"},
    {"text": "The competent programmer is fully aware of the strictly limited size of their own skull.", "author": "Edsger Dijkstra"},
    {"text": "If debugging is the process of removing bugs, then programming must be the process of putting them in.", "author": "Edsger Dijkstra"},
    {"text": "Measuring programming progress by lines of code is like measuring aircraft building progress by weight.", "author": "Bill Gates"},
    {"text": "Code never lies, comments sometimes do.", "author": "Ron Jeffries"},
    {"text": "Documentation is a love letter that you write to your future self.", "author": "Damian Conway"},
    {"text": "Good code is its own best documentation.", "author": "Steve McConnell"},
    {"text": "Before software can be reusable it first has to be usable.", "author": "Ralph Johnson"},
    {"text": "Optimism is an occupational hazard of programming; feedback is the treatment.", "author": "Kent Beck"},
    {"text": "One of the best programming skills you can have is knowing when to walk away for a while.", "author": "Oscar Godson"},
    {"text": "Sometimes it pays to stay in bed on Monday, rather than spending the rest of the week debugging Monday's code.", "author": "Dan Salomon"},
    {"text": "It always takes longer than you expect, even when you take into account Hofstadter's Law.", "author": "Douglas Hofstadter"},
    {"text": "There is not now, nor has there ever been, nor will there ever be, any programming language in which it is the least bit difficult to write bad code.", "author": "Flon's Law"},
    {"text": "Given enough eyeballs, all bugs are shallow.", "author": "Eric S. Raymond"},
    {"text": "Perfection is achieved not when there is nothing more to add, but when there is nothing left to take away.", "author": "Antoine de Saint-Exupery"},
    {"text": "The function of good software is to make the complex appear to be simple.", "author": "Grady Booch"},
    {"text": "Programming isn't about what you know; it's about what you can figure out.", "author": "Chris Pine"},
    {"text": "The best error message is the one that never shows up.", "author": "Thomas Fuchs"},
    {"text": "Weeks of coding can save you hours of planning.", "author": "Unknown"},
    {"text": "A language that doesn't affect the way you think about programming is not worth knowing.", "author": "Alan Perlis"},
    {"text": "Real programmers don't comment their code. If it was hard to write, it should be hard to understand.", "author": "Unknown"},
    {"text": "The trouble with programmers is that you can never tell what a programmer is doing until it's too late.", "author": "Seymour Cray"},
    {"text": "Computers are good at following instructions, but not at reading your mind.", "author": "Donald Knuth"},
    {"text": "An algorithm must be seen to be believed.", "author": "Donald Knuth"},
    {"text": "The most important property of a program is whether it accomplishes the intention of its user.", "author": "C.A.R. Hoare"},
    {"text": "There are two ways of constructing a software design: make it so simple there are obviously no deficiencies, or make it so complicated there are no obvious deficiencies.", "author": "C.A.R. Hoare"},
    {"text": "Object-oriented programming offers a sustainable way to write spaghetti code.", "author": "Paul Graham"},
    {"text": "A user interface is like a joke. If you have to explain it, it's not that good.", "author": "Martin LeBlanc"},
    {"text": "Good design adds value faster than it adds cost.", "author": "Thomas C. Gale"},
    {"text": "Design is not just what it looks like and feels like. Design is how it works.", "author": "Steve Jobs"},
    {"text": "The advance of technology is based on making it fit in so that you don't really even notice it.", "author": "Bill Gates"},
    {"text": "Artificial intelligence is the science of making machines do things that would require intelligence if done by humans.", "author": "Marvin Minsky"},
    {"text": "A distributed system is one in which the failure of a computer you didn't even know existed can render your own computer unusable.", "author": "Leslie Lamport"},
    {"text": "In theory, theory and practice are the same. In practice, they are not.", "author": "Yogi Berra"},
    {"text": "Machine learning is the last invention that humanity will ever need to make.", "author": "Nick Bostrom"},
    {"text": "Data is the new oil.", "author": "Clive Humby"},
    {"text": "Security is always excessive until it's not enough.", "author": "Robbie Sinclair"},
    {"text": "The internet is the first thing that humanity has built that humanity doesn't understand.", "author": "Eric Schmidt"},
    {"text": "A computer would deserve to be called intelligent if it could deceive a human into believing that it was human.", "author": "Alan Turing"},
    {"text": "Version control is a time machine for your code.", "author": "Unknown"},
    {"text": "Move fast and break things, unless you are breaking customers.", "author": "Mark Zuckerberg"},
    {"text": "Continuous integration doesn't get rid of bugs, but it does make them dramatically easier to find and remove.", "author": "Martin Fowler"},
]
